# https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: CI

on:
  push:
    branches:
      - '*'
    tags:
      - '[0-9]*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: gradle/wrapper-validation-action@v1

      - name: Setup Java 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Cache Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            !~/.gradle/caches/modules-2/modules-2.lock
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish snapshot to oss.sonatype.org
        run: ./gradlew publish "-Dorg.gradle.internal.publish.checksums.insecure=true"
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        if: |
          github.event_name == 'push' &&
          github.ref == 'refs/heads/master' &&
          github.repository == 'JFormDesigner/jide-oss'

      - name: Publish to Maven Central
        run: ./gradlew clean publish -Drelease=true
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY:      ${{ secrets.SIGNING_KEY }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
        if: |
          github.event_name == 'push' &&
          startsWith( github.ref, 'refs/tags/' ) &&
          github.repository == 'JFormDesigner/jide-oss'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: |
            build/libs

      - name: Print Gradle toolchains
        run: ./gradlew -q javaToolchains
